name: build-binary

on:
  push:
    branches: ["main", "release", "develop"]
  pull_request:
    branches: ["main", "release", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./cmd/main.go

    - name: Test
      run: go test -v ./...

    - uses: actions/upload-artifact@v4
      with:
        name: main
        path: ./main



